# Generated by Django 5.0.7 on 2025-04-15 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_servicetype_service_servicecashdinomination_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
