# Generated by Django 5.0.7 on 2025-04-15 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_service_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.shop'),
        ),
    ]
