# Generated by Django 5.0.7 on 2025-04-18 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_service_shop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.shop'),
        ),
    ]
